=== joostit/vfradar/Data/xmlSchemas/vfradarSite.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="vfradarSite">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="reportingpoints" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="runways" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="routes" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="runways">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="runway" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="routes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="route" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="route">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="point" minOccurs="2" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="runway">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="width" type="xs:double"/>
        <xs:element name="from" type="runwayHeadType"/>
        <xs:element name="to" type="runwayHeadType"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string"  use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="runwayHeadType">
    <xs:sequence>
      <xs:element ref="point"/>
    </xs:sequence>
    <xs:attribute name="name" use="required"/>
  </xs:complexType>
  

  <xs:element name="reportingpoints">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="reportingPoint" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="reportingPoint">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="point"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>


  <xs:element name="point">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="LatLonType">
          <xs:attribute name="name" type="xs:string" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>


  <xs:simpleType name="LatLonType">
    <xs:restriction base="xs:token">
      <xs:pattern value="^(\-?\d+(\.\d+)?),\s*(\-?\d+(\.\d+)?)$"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== joostit/vfradar/Data/Sites/EHTW.xml
<?xml version="1.0"?>
<vfradarSite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.vfradar.com/ vfradarSite.xsd">

  <reportingpoints>
    <reportingPoint name="Tango">
      <point>52.2929031, 6.6399750</point>
    </reportingPoint>
    <reportingPoint name="X-Ray">
      <point>52.323495, 6.724956</point>
    </reportingPoint>
    <reportingPoint name="Yankee">
      <point>52.312747, 6.851478</point>
    </reportingPoint>
    <reportingPoint name="Oscar">
      <point>52.292427, 6.871874</point>
    </reportingPoint>
  </reportingpoints>

  <runways>
    <runway name="EHTW">
      <width>45</width>
      <from name="05">
        <point>52.268293, 6.871564</point>
      </from>
      <to name="23">
        <point>52.283316, 6.906594</point>
      </to>
    </runway>
  </runways>

  <routes>
    <route name="EHTW_GA_inbound">
      <point name="Tango">52.2929031, 6.6399750</point>
      <point name="X-Ray">52.323495, 6.724956</point>
      <point name="Yankee">52.312747, 6.851478</point>
      <point name="Oscar">52.292427, 6.871874</point>
    </route>
  </routes>

</vfradarSite>
